---
name: Build Docker Image
on:
- pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build and Publish Docker Image
      id: docker
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        dockerfile: build/Dockerfile
        name: anchorfree/kafka-ambassador
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
